site_name: API Sample Documentation
site_description: Documentation for the API Sample service
site_author: Karned Team
site_url: https://karned-rekipe.github.io/api-sample/

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - autorefs

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference:
    - Overview: api/overview.md
  - Development:
    - Setup: development/setup.md
    - Contributing: development/contributing.md
    - GitHub Pages: development/github-pages.md
    - Code Coverage: development/code_coverage.md
